package mypack;
// Generated 11 Mar, 2019 10:24:49 AM by Hibernate Tools 4.3.1



/**
 * Userrs generated by hbm2java
 */
public class Userrs  implements java.io.Serializable {


     private String firstname;
     private String lastname;

    public Userrs() {
    }

	
    public Userrs(String firstname) {
        this.firstname = firstname;
    }
    public Userrs(String firstname, String lastname) {
       this.firstname = firstname;
       this.lastname = lastname;
    }
   
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


